// khai báo các const action cho reducer
export const ADD_SONG_TO_LIBRARY = 'ADD_SONG_TO_LIBRARY';

export const REMOVE_SONG_IN_LIBRARY = 'REMOVE_SONG_IN_LIBRARY';

export const ADD_PLAYLIST_TO_LIBRARY = 'ADD_PLAYLIST_TO_LIBRARY';

export const SET_ACTIVE_GET_NAME_MV = 'SET_ACTIVE_GET_NAME_MV';

export const SET_ACTIVE_GET_NAME_HISTORY = 'SET_ACTIVE_GET_NAME_HISTORY';

export const PLAY_MUSIC = 'PLAY_MUSIC';

export const MUSICS_OF_PAGE = 'MUSICS_OF_PAGE';

export const ADD_PLAYLIST_TO_HISTORY = 'ADD_PLAYLIST_TO_HISTORY';

//Icon
export const SET_ACTIVE_GET_ICON_VOLUME = 'SET_ACTIVE_GET_ICON_VOLUME';

export const SET_ACTIVE_GET_IS_PLAY = 'SET_ACTIVE_GET_IS_PLAY';

export const SET_ACTIVE_GET_IS_RANDOM = 'SET_ACTIVE_GET_IS_RANDOM';

export const SET_ACTIVE_GET_IS_LOOP = 'SET_ACTIVE_GET_IS_LOOP';


